# Site settings
title: Elliott's page
description: >
    Personal website of David Elliott Perryman
author: David Elliott Perryman
email: elliott.perryman@hey.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elliottperryman.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  elliottperryman

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
